name: Deploy-Remix-App

on:
  push:
    branches: [main]
    # paths:
    #   - "my-remix-app/**"

run-name: "Deploy brand_site to staging: ${{ github.sha }}"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    defaults:
      run:
        working-directory: my-remix-app
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - uses: actions/setup-node@v4
        timeout-minutes: 5
        with:
          node-version-file: ./my-remix-app/package.json

      - uses: pnpm/action-setup@v3
        with:
          package_json_file: ./my-remix-app/package.json

      - name: Install dependencies
        run: |
          pnpm install

      - name: D1 migrations apply
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: my-remix-app
          command: d1 migrations apply remix-demo-db --remote

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: my-remix-app
          preCommands: pnpm build
          command: pages deploy
