name: Deploy-Remix-App

on:
  push:
    branches: [main]
    paths:
      - "my-remix-app/**"

run-name: "Deploy brand_site to staging: ${{ github.sha }}"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Migrate Schema to Remote D1
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: my-remix-app
          packageManager: pnpm
          command: pnpm run-migration --remote

      - name: Deploy App
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: my-remix-app
          packageManager: pnpm
          command: pnpm deploy
